// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLfM73QgWZAPK6DXpcKyyZbpajNvPeWc',
    appId: '1:1001459572576:web:cda681fb5b834f6a310805',
    messagingSenderId: '1001459572576',
    projectId: 'pendaftaran-ujian-88943',
    authDomain: 'pendaftaran-ujian-88943.firebaseapp.com',
    storageBucket: 'pendaftaran-ujian-88943.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEx4SB2MRiURzfDwXLestaxMAWkb5CzXo',
    appId: '1:1001459572576:android:79a25cb9ddb041cf310805',
    messagingSenderId: '1001459572576',
    projectId: 'pendaftaran-ujian-88943',
    storageBucket: 'pendaftaran-ujian-88943.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm_8SToeqZsuxFSvFzIrnysJN1FEykK8s',
    appId: '1:1001459572576:ios:97bde535d2aeae28310805',
    messagingSenderId: '1001459572576',
    projectId: 'pendaftaran-ujian-88943',
    storageBucket: 'pendaftaran-ujian-88943.appspot.com',
    iosClientId: '1001459572576-buuon2k9b5087jj02tmgvnvbdnukpeen.apps.googleusercontent.com',
    iosBundleId: 'com.example.pendaftaranUjian',
  );
}
